# themes.yaml - Default theme configuration settings for Retiled.
# Windows Phone and all other related copyrights and trademarks are property
# of Microsoft Corporation. All rights reserved to Microsoft for Microsoft's 
# copyrights and trademarks.
#
# This file is a part of the Retiled project.
# Neither Retiled nor Drew Naylor are associated with Microsoft
# and Microsoft does not endorse Retiled.
# Any other copyrights and trademarks belong to their
# respective people and companies/organizations.
#
#
#   Due to this file essentially being a configuration file, this file
#   may be used in any form for any purpose and is not restricted by
#   any license. If this paragraph results in this file being incompatible
#   with the license of a project you'd like to use it with,
#   then the MIT License applies to this file as follows:
#
#      Copyright (C) 2022 Drew Naylor
# 
#      Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated 
#      documentation files (the “Software”), to deal in the Software without restriction, including without limitation 
#      the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and 
#      to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# 
#      The above copyright notice and this permission notice shall be included in all copies or substantial portions 
#      of the Software.
# 
#      THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED 
#      TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
#      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
#      CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
#      IN THE SOFTWARE.
#

# This file is heavily modified from the startlayout.yaml spec, which was in turn partially based on the winget installer manifest spec.



[ThemeSettings]
#   AccentColor is what's used to highlight the user interface, for example, to show when a button is pressed in,
# as well as the fill color on most tiles (if they aren't overriding the user's Accent color in their .desktop files).
#   You can probably use pretty much any hex color code you want here, but named colors have to be spelled correctly.
#   If something is wrong or missing, it's supposed to be replaced with the default, that being Cobalt ("#0050ef"),
# or whatever color a packager decided should be the default. Right now, there's no easy way to change the default
# aside from editing the source files.
AccentColor="#0050ef"
#   ThemeType is what Windows Phone referred to as "Background" in start+theme settings.
#   By default, the only choices are "light" (mostly white) and "dark" (mostly black), though only "dark" is currently implemented and
# this setting will be ignored until "light" is available. Changing it now will make your theme "light" when
# it's implemented.
#   Other themes (including transparent ones) would have to have support fine-tuned for them,
# although a simple config file saying what each control should have as a background color should be enough
# to provide this type of customization. It'll take more effort to provide support for third-party themes, though.
#   If it turns out to be simple enough to do, there will eventually be support for themes besides the default ones
# included with Retiled.
ThemeType="dark"
ThemesConfigSchemaVersion=0.1